### ISSUE TITLE
doi2ietf crashes on a DOI that has "editor" but no "author"

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/doi2ietf-py#8]
From a gentleman Alon Ben Refael:

> The above module is really great. Thank you!
>
> I would like to turn your attention to the fact that not all doi's work correctly.
>
> Here is an example:
```
10.1002/9783527647941
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "~/.local/lib/python3.8/site-packages/doi2ietf/utils.py", line 285, in process_doi_list
return parse_doi_data(data_lst, xml_output)
File "~/.local/lib/python3.8/site-packages/doi2ietf/utils.py", line 253, in parse_doi_data
ascii_lowercase[i]: transform_doi_metadata(doi_data)
File "~/.local/lib/python3.8/site-packages/doi2ietf/utils.py", line 72, in transform_doi_metadata
result["author"] = author_name(data["author"])
KeyError: 'author'
```
>
> I guess it's because there is no author, rather than an "editor" in the METADATA.

So we shouldn't crash when there is no author, and need to handle the case of "editor".

**Comment by yablokov** [comment]
@ronaldtse ok, I will fix it now and add this case (10.1002/9783527647941) to tests.

But [original ruby script](https://github.com/cabo/kramdown-rfc2629/blob/master/bin/doilit) does not handle case of "editor" (it just ignoring this field).

I will add editor data as `<author>` with `role="editor"`, as it described at [rfc7749 sec. 2.6.3](https://datatracker.ietf.org/doc/html/rfc7749#section-2.6.3). Also I will add this change to test fixtures.

If it correct, I can tag this fix as release.

**Comment by ronaldtse** [comment]
The format should follow RFC 7991 which isn’t so different from RFC 7799. 

The proposed fix should be correct, just help double check. Thanks!

**Comment by ronaldtse** [comment]
Yes this library should work better than the original script 😉

**Comment by ronaldtse** [comment]
@yablokov since the commit e9298fd fixes this issue, can you help make a new release? You just need to tag it and it should auto-release. Thanks.

**Comment by yablokov** [comment]
Ok, update published to [PyPi](https://pypi.org/project/doi2ietf/).

But I have a question. If we change output strictly according to RFC 7991, we lost full compatibility with original `doilit`. 

I thought it would be full analogue of `doilit` with same behavior to be compatible with some third party CI, pipelines, tests, etc.

So, if `doi2ietf` should be just alternative implementation of converter DOI to RFC 7991, can I update tests and don’t use `doilit` output as reference for the future?

**Comment by ronaldtse** [comment]
@yablokov we don't actually care about `doilit` from this point onwards, so we should do whatever is correct (not necessarily compatible). Thanks!
